<div id="body" class="row">
<h2>Welcome to the Barcode Ticket System</h2>
<p>There are currently no public features for ticket purchasers.
If you have an account to manage this system, however, you may <?php
echo '<a href="' . $this->url(array('module' => 'panel', 'controller' => 'login')) . '">log in</a>'; ?>.</p>
<p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
</div>