<?php
$links = array(
	'<a href="' . $this->url(
		array(
			'module' => 'panel',
			'controller' => 'events',
			'action' => 'create')) . '">Create an Event</a>',
	'<a href="' . $this->url(
		array(
			'module' => 'panel',
			'controller' => 'import-sales')) . '">Import Ticket Sales</a>',
	'<a href="' . $this->url(
		array(
			'module' => 'panel',
			'controller' => 'tickets',
			'action' => 'manage-barcodes')) . '">Manage Barcodes</a>',
	'<a href="' . $this->url(
		array(
			'module' => 'panel',
			'controller' => 'tickets')) . '">Manage Tickets</a>',
	'<a href="' . $this->url(
		array(
			'module' => 'panel',
			'controller' => 'tickets',
			'action' => 'generate-pdf')) . '">Print Label Sheets</a>');
?>
<div id="body" class="row">
<h2>Welcome to the Barcode Ticket System</h2>
<p>As an authorized user of this system, you have access to the
following tools:</p>
<?php
echo $this->htmlList($links, null, null, false);
?>
</div>