<?php
$this->assign('pageTitle', 'BTS &raquo; Manage Tickets');
$this->headTitle('Manage Tickets');
$this->headScript()->appendFile(
	'//ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js')
->appendFile('//ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js');
$inactivateBgImage = $this->baseUrl('img/lock_closed_24.png');
$this->headStyle(<<<STYLESHEET
table, td {
	border: 1px solid #ccc;
	border-collapse: collapse;
}
thead th {
	background-color: #888;
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0, rgb(180,
		178, 180) ), color-stop(1, #777) );
	background: -moz-linear-gradient(center top, rgb(180, 178, 180) 0%, #777
		100% );
	text-shadow: 1px 1px 5px #333;
	color: #eee;
}
td, th {
	padding: 0.2em 0.5em;
}
tbody tr:nth-child(odd) {
	background-color: #eee;
}
tr {
	text-align: center;
}
th.ticket_number {
	width: 10%;
}
th.attendee {
	width: 30%;
}
th.label {
	width: 15%;
}
td.label {
	font-family: monospace;
	text-transform: uppercase;
}
th.status {
	width: 10%;
}
th.actions {
	width: 10%;
}
td.actions a {
	display: inline-block;
	width: 24px; height: 24px;
	overflow: hidden; text-indent: -10000em;
	background-position: top center;
	border-bottom: none;
}
td.actions a.inactivate {
	background-image: url($inactivateBgImage);
}
#dialog-form { display: none; }
.ui-widget {
	font-size: 1em;
	font-family: "Palatino Linotype", Palatino, Georgia, Times,
		"Times New Roman", serif;
}
.ui-widget-content a {
	border-bottom: none;
}
.ui-widget fieldset {
	border: none;
}
STYLESHEET
)->appendStyle(<<<STYLESHEET
body {
	font-family: "Palatino Linotype", Palatino, Georgia, Times,
		"Times New Roman", serif;
}
th.ticket_number {
	width: 10%;
}
th.attendee {
	width: 30%;
}
th.label {
	width: 15%;
}
td.label {
	font-family: monospace;
	text-transform: uppercase;
	font-size: 1.15em;
}
th.status {
	width: 10%;
}
table, td, th {
	border: 1px solid #999;
	border-collapse: collapse;
}
td, th {
	padding: 0.2em 0.5em;
}
th {
	background-color: #cacaca;
}
tbody tr:nth-child(odd) {
	background-color: #eee;
}
#header-bar, #footer, td.actions, th.actions, td.actions a { display: none; }
STYLESHEET
, array('media' => 'print'));
$this->headLink()->appendStylesheet('//ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css');
$this->headScript()->appendScript('$(document).ready(function() {
	$( ".inactivate" ).click(function() {
		$( "#dialog-form" ).dialog( "open" );
	});
	$( "#dialog-form" ).dialog({
			autoOpen: false,
			height: 300,
			width: 350,
			modal: true,
			buttons: {
				"Update":function(){},
				"Cancel": function() {
					$(this).dialog("close");
				}
			},
			close: function() {
				$("#dialog-form input").val( "" ).removeClass( "ui-state-error" );
			}
	});
});');
?>
<div id="body" class="row">
<div class="column grid_10">
<p>You are viewing the ticket list for the event named <strong><?php echo $this->eventRow->name; ?></strong>.</p>
<table>
	<thead>
		<tr>
			<th class="ticket_number">Ticket #</th>
			<th class="attendee">Attendee</th>
			<th class="label">Label</th>
			<th class="status">Status</th>
			<th class="actions"></th>
		</tr>
	</thead>
	<tbody>
<?php
foreach ($this->tickets as $t) {
	echo <<<TICKET
		<tr>
			<td class="ticket_number">{$t['ticket_id']}</td>
			<td class="attendee">{$t['first_name']} {$t['last_name']}</td>
			<td class="label">{$t['event_id']}-{$t['batch']}-{$t['ticket_id']}-{$t['checksum']}</td>
			<td class="status">{$this->ticketStatuses[$t['ticket_id']]}</td>
			<td class="actions">
				<a href="#" title="Inactivate" id="inactivate_{$t['ticket_id']}" class="inactivate">Inactivate</a></td>
		</tr>
TICKET;
}
?>
</tbody>
</table>
</div>
</div>


<div id="dialog-form" title="Invalidate ticket">
	<p class="validateTips">All form fields are required.</p>

	<form>
	<fieldset>
		<label for="salesperson">Salesperson</label>
		<input type="text" name="salesperson" id="salesperson" value="" class="text ui-widget-content ui-corner-all" />
	</fieldset>
	</form>
</div>