<?php

/**
 * Installer model.
 *
 * Contains methods for setting up BTS server for the first time.
 *
 * @author	Frederick Ding
 * @package	Bts
 */
class Bts_Model_Installer
{

	/**
	 * Generates a pseudorandom 256-bit installation hash.
	 *
	 * By default, it will try to use OpenSSL to make random bytes, but in case
	 * OpenSSL is unavailable, it falls back to a random-number-seeded hash of
	 * installation details. (The OpenSSL-generated bytes are used as-is; they
	 * are not further hashed.)
	 *
	 * In previous versions, installation instructions recommended using a
	 * 32-character (256-bit) human-readable ASCII string. This installer will
	 * instead produce a hex representation of a true 256-bit hash.
	 *
	 * @since 0.2.0
	 * @return string
	 */
	public static function generateHash ()
	{
		$hash = '';
		if (extension_loaded('openssl') &&
				 version_compare(PHP_VERSION, '5.3.0', '>=')) {
			$hash = bin2hex(openssl_random_pseudo_bytes(32));
		} else {
			// fallback to sha256 of installation details + 32-char salt
			$plaintext = $_SERVER['SERVER_ADDR'] . $_SERVER['HTTP_HOST'] .
					 $_SERVER['SCRIPT_FILENAME'];
			// produce a 32-char salt using printable ASCII characters
			for ($i = 0; $i < 32; $i ++) {
				$plaintext .= chr(mt_rand(32, 126));
			}
			$hash = hash('sha256', $plaintext);
		}
		return $hash;
	}

}