<?php
$this->headTitle('Error');
$this->assign('pageTitle', 'BTS &raquo; An Error Occurred');
?>
<div id="body" class="row">
<div class="column grid_10">
<h2><?php
echo $this->message?></h2>

<?php
if (isset($this->exception)) :
	?>

<h3>Exception information:</h3>
<p><b>Message:</b> <?php
	echo $this->exception->getMessage()?>
  </p>

<h3>Stack trace:</h3>
<pre style="overflow: scroll;"><?php
	echo $this->exception->getTraceAsString()?>
  </pre>

<h3>Request Parameters:</h3>
<pre><?php
	echo var_export($this->request->getParams(), true)?>
  </pre>




<?php endif ?>
</div>
</div>