<?php
$this->assign('pageTitle', 'BTS &raquo; Login');
$this->headTitle('Login');
$this->headStyle(
	'#login {
	border-right: 1px solid #999;
	margin-right: 9px;
}

#login ul ul.errors {
	padding-left: 1em;
}

#login ul ul.errors li {
	list-style: none;
}

#login form p {
	margin-left: 1em;
}

#login input {
	margin-right: 0.5em;
}');
?>
<!-- warnings for Javascript and IE -->
<noscript>
<div class="row error">
<div class="column grid_10">Error: BTS requires the use of
Javascript and does not function without it.<br />
Please enable Javascript in your browser.</div>
</div>
</noscript>
<!--[if IE]>
	<div class="row warning">
	<div class="column grid_10"> Warning: BTS was designed for modern browsers like <a href="http://www.mozilla.com/firefox/">Firefox</a> and <a href="http://www.google.com/chrome">Chrome</a>.<br />
		Please upgrade your browser; stop using IE! </div>
	</div>
	<![endif]-->
<div id="body" class="row">
<div id="login" class="column grid_6">
<h2>login</h2>
<?php
echo $this->formObject;
?>
<p><a href="#">Forgot your password?</a></p>
</div>
<div id="register" class="column grid_4">
<h2>register</h2>
<p>A user account is needed to use this control panel or the software clients.</p>
</div>
</div>
