<?php
$this->assign('pageTitle', 'BTS &raquo; Installer');
$this->headTitle('Installer Step 2');
$this->declareVars('config', 'hash', array('error' => false), 'exception');
?>
<div id="body" class="row">
	<h2>2. Initialize cryptography</h2>
<?php if($this->error == 'write') { ?>
	<p class="notice bad">We weren't able to write a new configuration file to 
	<code>application/configs/bts.ini</code>, but you can set it up yourself by 
	copying the	contents below to a new file there.</p>
	<p><small>Usually, you can also fix this by chmoding the <code>configs</code> 
	directory to 777 and refreshing the page.</small></p>
	<pre><?php echo $this->config; ?></pre>
<?php } elseif($this->error == 'exists') { ?>
	<p class="notice bad">Looks like you've already set up your configuration  
	in <code>application/configs/bts.ini</code>. The installer won't 
	automatically overwrite	it, but you can set it up again yourself by copying 
	the contents below to it.</p>
	<pre><?php echo $this->config; ?></pre>
	<p>You can also go to the next step without doing anything. We will simply 
	continue to use your existing <code>bts.ini</code> configuration.</p>
<?php } else { ?>
	<p class="notice good">We've set up your configuration file with a new 
	secret hash, which is used to seed encryption in BTS. You may want to keep 
	this in a safe place.</p>
	<pre><?php echo $this->hash; ?></pre>
<?php } ?>

	<?php
	echo '<a class="prev" href="' . $this->url(
			array(
					'module' => 'default',
					'controller' => 'install',
					'action' => 'test'
			)) . '"><span>Back</span></a>';
	if($this->error != 'write') {
		echo '<a class="next" href="' . $this->url(
				array(
						'module' => 'default',
						'controller' => 'install',
						'action' => 'database'
				)) . '"><span>Next</span></a>';
	}
	?>
</div>