<?php
$this->assign('pageTitle', 'BTS &raquo; Installer');
$this->headTitle('Installer');
?>
<div id="body" class="row">
	<h2>Welcome</h2>
	<p>Welcome to your soon-to-be installation of the Barcode Ticket System
		(BTS). BTS integrates with API clients to enable convenient and secure
		electronic tickets for events.</p>
	<p>It looks like you need to set up the BTS server for the first time.
		Before we begin, please check that your web host meets these
		minimum requirements:</p>
	<ul>
		<li>PHP 5.3+<br />
			with <a href="http://pear.php.net/">PEAR</a>, 
			<a href="http://php.net/manual/en/book.mcrypt.php">mcrypt</a>, and 
			<a href="http://php.net/manual/en/ref.pdo-mysql.php">PDO MySQL</a> 
			(preferred) or 
			<a href="http://php.net/manual/en/book.mysqli.php">MySQLi</a></li>
		<li>MySQL 5+ database with InnoDB</li>
		<li>Write access to the filesystem</li>
	</ul>
	<?php
	echo '<a class="next" href="' . $this->url(
			array(
					'module' => 'default',
					'controller' => 'install',
					'action' => 'test'
			)) . '"><span>Begin</span></a>';
	?>
</div>