<?php
$this->assign('pageTitle', 'BTS &raquo; Installer');
$this->headTitle('Installer Step 1');
?>
<div id="body" class="row">
	<h2>Test your server</h2>
	<p>The installer has checked your server for required modules.</p>
	<table style="width: 500px">
		<tbody>
<?php foreach($this->tests as $test => $result) : ?>
			<tr>
				<td>
					<?php echo $this->testReadable[$test][0]; ?>
				</td>
				<td class="<?php echo ($result ? 'good' : 'bad'); ?>">
					<?php echo ($result ? $this->testReadable[$test][1] : 
						$this->testReadable[$test][2]); ?>
				</td>
			</tr>
<?php endforeach; ?>
		</tbody>
	</table>	
	<?php
	echo '<a class="next" href="' . $this->url(
			array(
					'module' => 'default',
					'controller' => 'install',
					'action' => 'hash'
			)) . '"><span>Begin</span></a>';
	?>
</div>